services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.95.3
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      n8n_network:
        ipv4_address: 192.168.3.2
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: n8n
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      n8n_network:
        ipv4_address: 192.168.3.3
    ports:
      - "3306:3306"
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      n8n_network:
        ipv4_address: 192.168.3.4
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      n8n_network:
        ipv4_address: 192.168.3.5
    environment:
      - PGADMIN_DEFAULT_EMAIL=EMAIL
      - PGADMIN_DEFAULT_PASSWORD=PASSWORD  
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4000:80
    links:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      n8n_network:
        ipv4_address: 192.168.3.6
    restart: unless-stopped
    volumes:
      - redis_data:/data

  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: unless-stopped
    networks:
      n8n_network:
        ipv4_address: 192.168.3.7
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances


volumes:
  n8n_data:
  mysql_data:
  postgres_data:
  pgadmin_data:
  redis_data:
  evolution_store:
  evolution_instances:

networks:
  n8n_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24